### PR TITLE
[WIP] Add type annotations for client and client_async

### PR DESCRIPTION
**Pull request by swamper123**
Start adding type annotations like mentioned in #157 .

Helping hands are welcomed :)

### CODE REVIEW

**Comment by gijzelaerr** [comment]
cool, thanks. Maybe we should add some docker mypy run to travis also, similar to this project:

https://github.com/eduvpn/python-eduvpn-client/blob/master/docker/eduvpn_ubuntu_bionic_py3_mypy.docker

and when we are at it, also a pycodestyle:

https://github.com/eduvpn/python-eduvpn-client/blob/master/docker/eduvpn_ubuntu_bionic_py3_pep8.docker

that way we are for sure no broken code gets checked into the repo (anymore).

**Comment by swamper123** [comment]
@gijzelaerr I never worked with dockers before (and not the time at the moment), so I will not be a great help in that case.

But what would mypy run do, compared to the other existing stuff in travis? What would be the advantage?

Pycodestyle can be usefull, but wouldn't pylint be better to check styles?

**Comment by gijzelaerr** [comment]
i'm also quite busy so i have very little time for this kind of things, but answering your questions between work is possible for me.

having a docker container on Travis enables us to run these tools for every PR, so we/others don't need to do it manually. 

pylint is much more pedantic than pycodestyle, which is not necessarily a bad thing but it will take more time to adjust the code to its likings. pycodestyle is a good start to check for pep8 compatibility.

**Comment by swamper123** [comment]
@gijzelaerr Hmm...if I make a PR, Travis starts on it's own running all its stuff. I never had to push a button or similar, no clue if other contributors have such a problem.

Well we could start with pylint as well. Something is better than nothing. 😄

**Comment by gijzelaerr** [comment]
That travis runs on every PR is the whole point right? That way we check of the PR is good. so if we do a mypy and pycodestyle for every PR we are sure no bad code ends up in master.

**Comment by swamper123** [comment]
In Case somebody wants to help, I want to mentioned some hints/cases:
- f-strings and bytes may bite. Perhaps `fr` prefix may fix it [Conclusion: TBH]
- Check if methods are equal to parent class
- --> Union[type1, type2, ...] says explicit that type1, type2 ... can be returned
- --> Optional[type1] says, that type1 or None can be returned

**Pull request closed without merging**
