### PR TITLE
Added GET SET small_int support functions, and to the class DB_Row

### PR DESCRIPTION
**Pull request by lautarodapin**
I added the following functions to the `snap7.util` module.
```python
def get_small_int(bytearray_, byte_index):
    """
    Get small int value from bytearray.

    small int is represented as 1 byte
    """
    data = bytearray_[byte_index] & 0xff
    packed = struct.pack('B', data)
    value = struct.unpack('>B', packed)[0]
    return value


def set_small_int(bytearray_, byte_index, _int):
    """
    Set value in bytearray to int

    small int is represented as 1 byte
    """
    _int = int(_int)
    _bytes = struct.unpack('B', struct.pack('>B', _int))
    bytearray_[byte_index] = _bytes[0]
    return bytearray_

```

Also added to the methods `get_value` and `set_value` of the ``` class DB_Row``` the following part:
```python
if _type == 'SINT':
    return get_small_int(_bytearray, byte_index)

if _type == 'SINT':
    return set_small_int(_bytearray, byte_index, value)

```

### CODE REVIEW

**Comment by gijzelaerr** [comment]
awesome, thanks!

Can you have a look at the output of the pycodestyle check? That check is not happy with these lines:

```
snap7/util.py:328:1: E303 too many blank lines (3)
snap7/util.py:559:27: W291 trailing whitespace
test/test_util.py:41:107: W291 trailing whitespace
test/test_util.py:118:1: W293 blank line contains whitespace
test/test_util.py:120:5: E303 too many blank lines (2)
test/test_util.py:235:1: W293 blank line contains whitespace
test/test_util.py:237:5: E303 too many blank lines (3)
```

**Comment by lautarodapin** [comment]
I just realized that the structure I added isn't really a small int, because it goes from 0 to 254, this should be called unsigned small int

**Comment by gijzelaerr** [comment]
hi! thanks for your PR. 

There is an issue with the formatting again/still though:
```
snap7/util.py:343:1: W293 blank line contains whitespace
snap7/util.py:387:34: W291 trailing whitespace
snap7/util.py:600:27: W291 trailing whitespace
test/test_util.py:42:106: W291 trailing whitespace
test/test_util.py:247:1: W293 blank line contains whitespace
test/test_util.py:249:5: E303 too many blank lines (3)
```

You can see these issues for yourself if you press the red X behind a commit, that is a travis job that runs the unittests and checks python formatting and pep8 errors:

https://travis-ci.org/github/gijzelaerr/python-snap7/jobs/718250112

**Comment by gijzelaerr** [comment]
awesome, thanks!

**Pull request merged**
