### PR TITLE
implement as_b_send b_send and b_recv for Partner connection.

### PR DESCRIPTION
**Pull request by wilkpio**
Support for  b_send and b_recv in Partner mode.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
the travis test suite is failing, can you have a look?

https://travis-ci.org/gijzelaerr/python-snap7/jobs/67027448

**Comment by wilkpio** [comment]
Does it execute tests for different platforms in parallel?
My experience with Partner mode is that there could be only one connection
at the time.
In case IP/Port/TSAP is already in use the connection will simply fail :(
Is it somehow possible to serialize tests for different platforms in travis?

br,
Piotr

best regards
Piotr Wilkosz
Disclaimer: Any errors in spelling, tact, or fact are transmission errors.

**Comment by gijzelaerr** [comment]
Every tests suits is run in a VM, so they should not interfere.

**Comment by gijzelaerr** [comment]
Sorry for the delay looking at this.

Your PR looks very good. But I'm trying to get this working on a mac, but I don't understand why it doesn't work. 

```
passive = snap7.partner.Partner(active=False)
active = snap7.partner.Partner(active=True)
passive.start_to("0.0.0.0", "127.0.0.1", 1002, 1000)
active.start_to("0.0.0.0", "127.0.0.1", 1000, 1002)
active.get_status().value
1 # (Running, active and trying to connect.)
passive.get_status().value
2 # (Running, passive and waiting for a connection)
```

**Comment by gijzelaerr** [comment]
actually I'm seeing the same results on a Linux machine, they don't seem to connect and the test fails.

I'm trying this with snap7 1.4.0 on Ubuntu 15.04 and OSX 10.10.5.

**Comment by gijzelaerr** [comment]
When this issue has been solved I'll release 0.5 and include these changes.

**Pull request closed without merging**
