### PR TITLE
Enhancement to support indented db specifications. Fixes #133

### LINKED ISSUE #133: Can't handle indented DB layout specification
Requesting enhancement to util's parse_specification() so it can handle indented DB layout specifications.

This just requires the addition of lstrip() to the line processing.

`
        if line and not line.lstrip().startswith('#'):
`

### PR DESCRIPTION
**Pull request by ronkinoz**
Reworked line processing in parse_specification() such that indented db specifications are now supported.

### CODE REVIEW

**Comment by spreeker** [comment]
The first two lines remove lines with comments.
The added line removes trailing comments
They are BOTH needed..

**Comment by gijzelaerr** [comment]
i guess a proper unit test is required to verify these cases.

**Comment by gijzelaerr** [comment]
If a proper unit test is added I'll merge this change.

Thanks all.

**Comment by gijzelaerr** [comment]
superseded by https://github.com/gijzelaerr/python-snap7/pull/254

**Pull request closed without merging**
