### PR TITLE
Added get_block_info wrapper for Cli_GetAgBlockInfo

### PR DESCRIPTION
**Pull request by victorclaessen**
Hi, this is my first github pull request, so I hope I'm doing this right.

I added a wrapper for the Snap7 Cli_GetAgBlockInfo C function, and also added the required TS7BlockInfo structure.

### CODE REVIEW

**Comment by spreeker** [comment]
victorclaessen thanks for the effort!! I cleanup your code to comply with pep8 and the coding styles we use in this project.

The Travis CI build could not complete due to an error. I did some cleanup and fixed the missing imports
everything seems to work. 

It would be nice if you created a test for your function!

**Comment by gijzelaerr** [comment]
I would say dont merge without test :)

Op di 24 feb. 2015 20:10 schreef stephan preeker <notifications@github.com>:

**Comment by spreeker** [comment]
I tried to test it... item not available.

**Comment by victorclaessen** [comment]
Hi, thanks for helping me out. I had not yet discovered the unit test functions. I'm not exactly sure what you would like me to do.

**Comment by spreeker** [comment]
Well a lot of functions in the client has a test function in
test/test_client.py

Running run_tests will run all tests of all. Modules and create a virtual
test plc against which the client can be tested.

But the get_block_info function cannot be tested I tried. Works only on a
real plc I think.

Have a look at the tests and how it's works it's educational.

Stephan.

**Comment by victorclaessen** [comment]
Ah, ok, I think I got it now. The get_block_info test that you made was just requesting a non-existing block (i.e. there is no DB10 in the test_server, but there is a DB1). If you change the block number from 10 to 1, it works.

**Comment by spreeker** [comment]
Awesome..  Well I tried to create a db10 in the server code. The Test
failed so I removed it :)  but perfect that it just works now! Tests are
important.

@gijs  I always just used git rebase  but pull - - rebase is handy indeed.

**Pull request merged**
