### PR TITLE
add support for read/write byte from bytearray with tests

### PR DESCRIPTION
**Pull request by lautarodapin**
#262

### CODE REVIEW

**Comment by lautarodapin** [comment]
Well i create a new branch but the commits appear anyway D:

**Comment by gijzelaerr** [comment]
yeah still, something going wrong. Did you make a new fork of the python-snap7 repo? I think your master branch history diverged from the main one.  But I think that when I squash this PR the trouble on our side will disappear.

**Comment by lautarodapin** [comment]
> yeah still, something going wrong. Did you make a new fork of the python-snap7 repo? I think your master branch history diverged from the main one. But I think that when I squash this PR the trouble on our side will disappear.

Now I'm working on the documentation.
I made a new branch, but now I did a `checkout --orphan`, this what the initial commit is the lib itself.

**Comment by gijzelaerr** [comment]
making an orphan branch is something different, that means you are detached from our tree. I don't think this is what you want.

**Comment by gijzelaerr** [comment]
I recommend you completely remove your local fork and github fork, press fork again on github, clone your fork and start from there. Don't commit to master, always work on a working branch. regularly sync your master with our master.

**Pull request merged**
