### PR TITLE
add the readszl() function #196

### PR DESCRIPTION
**Pull request by nikteliy**
Feature request #196 

* add the function
* add types for a partial list and for the header of a partial list
* add tests

Code has been tested with 1200(151-214-1hg31-0xb0) and ET200S(151-8ab01-0ab0).
I'm not sure about the return type. Is it okay to return a ctypes.Structure? Or is it better to convert it to dict, for example?

### CODE REVIEW

**Comment by gijzelaerr** [comment]
Thank you for your contribution! Looking good and good question. I think I would use a named tuple unless you have a good argument against? I prefer to shield the user from the low-level details in a pythonic way.

**Comment by swamper123** [comment]
@gijzelaerr Intuitively I would make a dict out of it, since the structure invites to make one out of it (a tuple with a name and a value in a list).

**Comment by gijzelaerr** [comment]
I don't mean a tuple but a named tuple:

https://docs.python.org/3/library/collections.html#collections.namedtuple

I would argue this is the python equivalent of a struct since it preserves order, have a fixed set of properties and is prettier to use since it has property accessors. Since Python 3.9 dictionaries have an order also, but we support older pythons.

**Comment by swamper123** [comment]
Oh, I haven't known that such a thing exists...well in that case, this would be the better choice. Thanks for the info!

**Comment by nikteliy** [comment]
What if add [typing.NamedTuple](https://docs.python.org/3/library/typing.html#typing.NamedTuple) in types.py and use it as return type? We'll have typed namedtuple similar to dataclass.
```python
import typing

class SystemStatusListHeader(typing.NamedTuple):
    length_dr: int
    number_dr: int


class SystemStatusList(typing.NamedTuple):
    header: SystemStatusListHeader
    data: bytes
```

**Comment by gijzelaerr** [comment]
yes, I think that is perfect. Indeed, dataclass and namedtuple became more similar over time, but I think a named tuple is a bit leaner but I might be wrong.

thanks!

**Comment by gijzelaerr** [comment]
I now realise that this breaks consistency with the rest of the code. What do you think works better from a developer perspective, the structs or the named tuples @nikteliy ?  If it improves the usability maybe we should aim to move everything to named tuples in ht belong run if it is worth the effort, otherwise, it might be better to stick with keeping the structs.

**Comment by nikteliy** [comment]
> this breaks consistency with the rest of the code

In which way?
I don't see how it's possible to replace structures with tuples. They are at different levels of the application for me, as in the diagram.
pic1

**Comment by nikteliy** [comment]
I think I should revert the last commit. Functions should behave in the same way. Named tuples are not useful enough to break backward compatibility. And this pr is not about tuples. What do you think @gijzelaerr ?

**Comment by gijzelaerr** [comment]
Hehe, I love your drawing though :) 

I agree that shielding the scary low-level things is ideal, but this is not how python-snap7 has been set up initially. So maybe, for now, let's keep things consistent and maybe, at some point, we will switch to a more pythonic wrapping. Would be nice to get a 1.0 out the door someday, was planning to release that when the full API is implemented. for 2.0 I would like to switch to CFFI as a backend since that will make it possible/easy to create a binary wheel, eliminating many of the issues people experience while setting up python-snap7. 2.0 would be a good moment to switch to the pythonic type wrapping.

With the current pace of development that could be years away though :) I maintain this repo in my spare time, so unless someone pays me to rewrite the library I only accept PR's by developers like yourself and try to steer the project in the right direction.

thanks!

**Comment by nikteliy** [comment]
> let's keep things consistent

"If it's works, don't touch it"  is my motto :)

> Would be nice to get a 1.0 out the door someday

Where can I find a list of tasks ordered by priority?

**Comment by gijzelaerr** [comment]
The issue tracker :)

https://github.com/gijzelaerr/python-snap7/issues

although it is not really ordered. I want to make a 1.0 release if all bugs are resolved and all functions are implemented. Maybe the type hinting should be moved to 2.0 if the return types are going to change.

**Comment by nikteliy** [comment]
> all bugs are resolved and all functions are implemented

It's a lot of work. I'll see what I can do.

**Review by gijzelaerr — APPROVED** [review]

**Pull request merged**
