### PR TITLE
Add client functions

### PR DESCRIPTION
**Pull request by nikteliy**
* add functions
* add tests
* add types

### CODE REVIEW

**Comment by nikteliy** [comment]
What should I do with the names of the functions? Keep as is or replace with snake_case?

**Comment by swamper123** [comment]
Looks good on first sight. I guess snake_cases would be more uniform with the existing code.

**Comment by gijzelaerr** [comment]
this is awesome! thanks. Please use snake_case though, that was a regular expression mistake I made a while ago.

**Comment by swamper123** [comment]
Nice! 👍

**Comment by nikteliy** [comment]
> Nice! 👍

Thanks. I'm happy to help

**Comment by gijzelaerr** [comment]
perfect! thanks!

**Review by gijzelaerr — APPROVED** [review]

**Pull request merged**
