### PR TITLE
Fixed typo area doesn't exist areas does

### PR DESCRIPTION
**Pull request by Ofloo**
Typo in example file area doesn't exist I assume it's supposed to be areas

### CODE REVIEW

**Comment by gijzelaerr** [comment]
it looks like you are issuing a PR from an older checkout or version.

**Comment by Ofloo** [comment]
Made the checkout today about an hour ago ?

**Comment by Ofloo** [comment]
And the link in the comments also doesn't exist anymore

# https://github.com/gijzelaerr/python-snap7/blob/master/snap7/snap7types.py shoud be # https://github.com/gijzelaerr/python-snap7/blob/master/snap7/types.py

**Comment by Ofloo** [comment]
And i made mistake myself, .. it should in fact be Areas rather then areas because areas gets a type error while Areas doens't.

**Review by gijzelaerr — APPROVED** [review]

**Pull request merged**
